/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard.index'
import { Route as ApiWebhookSplatRouteImport } from './routes/api/webhook/$'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardDashboardSettingsRouteImport } from './routes/_dashboard/dashboard.settings'
import { Route as DashboardDashboardRunsRouteImport } from './routes/_dashboard/dashboard.runs'
import { Route as DashboardDashboardRepoIdRouteImport } from './routes/_dashboard/dashboard.$repoId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiWebhookSplatRoute = ApiWebhookSplatRouteImport.update({
  id: '/api/webhook/$',
  path: '/api/webhook/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardSettingsRoute =
  DashboardDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardRunsRoute = DashboardDashboardRunsRouteImport.update({
  id: '/dashboard/runs',
  path: '/dashboard/runs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRepoIdRoute =
  DashboardDashboardRepoIdRouteImport.update({
    id: '/dashboard/$repoId',
    path: '/dashboard/$repoId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard/$repoId': typeof DashboardDashboardRepoIdRoute
  '/dashboard/runs': typeof DashboardDashboardRunsRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhook/$': typeof ApiWebhookSplatRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard/$repoId': typeof DashboardDashboardRepoIdRoute
  '/dashboard/runs': typeof DashboardDashboardRunsRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhook/$': typeof ApiWebhookSplatRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_dashboard/dashboard/$repoId': typeof DashboardDashboardRepoIdRoute
  '/_dashboard/dashboard/runs': typeof DashboardDashboardRunsRoute
  '/_dashboard/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhook/$': typeof ApiWebhookSplatRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/dashboard/$repoId'
    | '/dashboard/runs'
    | '/dashboard/settings'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/webhook/$'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/dashboard/$repoId'
    | '/dashboard/runs'
    | '/dashboard/settings'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/webhook/$'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_dashboard/dashboard/$repoId'
    | '/_dashboard/dashboard/runs'
    | '/_dashboard/dashboard/settings'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/webhook/$'
    | '/_dashboard/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiWebhookSplatRoute: typeof ApiWebhookSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/webhook/$': {
      id: '/api/webhook/$'
      path: '/api/webhook/$'
      fullPath: '/api/webhook/$'
      preLoaderRoute: typeof ApiWebhookSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard/settings': {
      id: '/_dashboard/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardDashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/runs': {
      id: '/_dashboard/dashboard/runs'
      path: '/dashboard/runs'
      fullPath: '/dashboard/runs'
      preLoaderRoute: typeof DashboardDashboardRunsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/$repoId': {
      id: '/_dashboard/dashboard/$repoId'
      path: '/dashboard/$repoId'
      fullPath: '/dashboard/$repoId'
      preLoaderRoute: typeof DashboardDashboardRepoIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDashboardRepoIdRoute: typeof DashboardDashboardRepoIdRoute
  DashboardDashboardRunsRoute: typeof DashboardDashboardRunsRoute
  DashboardDashboardSettingsRoute: typeof DashboardDashboardSettingsRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRepoIdRoute: DashboardDashboardRepoIdRoute,
  DashboardDashboardRunsRoute: DashboardDashboardRunsRoute,
  DashboardDashboardSettingsRoute: DashboardDashboardSettingsRoute,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiWebhookSplatRoute: ApiWebhookSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
